
# References for the YAML syntax:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site
title: Thiago Scarelli
author: Thiago Scarelli
description: Thiago Scarelli is a Lecturer in the Department of Economics at the University of Oxford.
domain: thiagoscarelli.github.io
url: https://thiagoscarelli.github.io
lang: en_US
locale: en_US

# Social
name: Thiago Scarelli
email: thiago.scarelli@economics.ox.ac.uk
twitter_user: tscarelli
github_user: thiagoscarelli
orcid_user: '0000-0003-2014-2084'
stackoverflow_user: 9734152/thiago
linkedin_user: 'thiago-scarelli'

# Jekyll
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
