
# Variables for the whole site
# They can be accessed via {{ site.title }}, {{ site.email }}, and so on.

# References for the YAML syntax:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site
title: Thiago Scarelli
author: Thiago Scarelli
description: Thiago Scarelli is a Ph.D. candidate at the Paris School of Economics (PSE). His research focuses on the different forms of labor market participation in low- and middle-income countries, with a particular interest in the self-employed and the platform workers.
domain: thiagoscarelli.github.io
url: https://thiagoscarelli.github.io
lang: en_US
locale: en_US

# Social
name: Thiago Scarelli
email: thiago.scarelli@psemail.eu
twitter_user: tscarelli
github_user: thiagoscarelli
orcid_user: '0000-0003-2014-2084'
stackoverflow_user: 9734152/thiago
linkedin_user: 'thiago-scarelli'

# Jekyll
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
