theme: jekyll-theme-minimal
title: Thiago Scarelli
logo: /assets/img/logo.jpg
description: I'm a Ph.D Student at the Paris School of Economics under the supervision of David N. Margolis. My current research focus on occupational decisions in developing countries under liquidity constraints.
google_analytics: UA-175203179-1
