# Outputting
permalink: /:categories/:year/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Thiago Scarelli            # Site title
name:             Thiago Scarelli            # Your name
avatar:           /theme/img/thiagoscarelli.png      # Path to an avatar image
description:      Thiago Scarelli is a Ph.D. student at Paris School of Economics (PSE). His current research focuses on the occupational choices of workers in developing countries.
intro:            Ph.D. student at Paris School of Economics.
mail:             thiago.scarelli [at] psemail.eu

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the profile sidebar off for all pages by default
defaults:
  -
    scope:
      path: ""
    values:
      show_title: true
      show_profile: false
  -
    scope:
      path: "_posts"
    values:
      show_title: false
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "list"
    values:
      show_title: false
      show_profile: false
      layout: defaults/list
