# Outputting
permalink: /:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Thiago Scarelli            # Site title
name:             Thiago Scarelli            # Your name
avatar:           /theme/img/thiago-scarelli.jpg      # Path to an avatar image
description:      Thiago Scarelli is a Ph.D. student at Paris School of Economics (PSE). His current research focuses on the occupational choices of workers in developing countries. His main interests include applied statistics and econometric softwares.
intro:            Ph.D. student at Paris School of Economics.
mail:             thiago.scarelli [at] psemail.eu

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the profile sidebar off for all pages by default
defaults:
  -
    scope:
      path: ""
    values:
      show_title: true
      show_profile: false
  -
    scope:
      path: "_posts"
    values:
      show_title: false
      show_profile: false
      layout: post

# SEO optimization bits
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

logo:   /theme/img/thiago-scarelli.jpg
url:    https://thiagoscarelli.github.io/
lang:   en_US

social:
  name: Thiago Scarelli
  links:
    - https://twitter.com/tscarelli
    - https://www.linkedin.com/in/thiago-scarelli-36a4a634/
    - https://github.com/thiagoscarelli

google_site_verification: UK5Z3DkjNFOe8U_y4pFUaSc0cqYigDf3_JDHUIljLhM
