
# Variables for the whole site
# They can be accessed via {{ site.title }}, {{ site.email }}, and so on.

# References for the YAML syntax:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site
title: Thiago Scarelli
author: Thiago Scarelli
name: Thiago Scarelli
description: >- # this means to ignore newlines until "baseurl:"
  Thiago Scarelli is a Ph.D. candidate at the Paris School of Economics (PSE) and Université Paris 1 Panthéon-Sorbonne.
  My current research projects investigate the structure of labor markets in low and middle-income countries, with a particular interest in the relationship between financial stress and own-account work.
domain: thiagoscarelli.github.io
url: https://thiagoscarelli.github.io
lang: en_US
locale: en_US

# Social
email: thiagoscarelli@gmail.com
twitter_user: tscarelli
github_user: thiagoscarelli
orcid_user: '0000-0003-2014-2084'
stackoverflow_user: 9734152/thiago
linkedin_user: 'thiago-scarelli'

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Conversion
markdown: kramdown
highlighter: rouge

# Kramdown
kramdown:
  math_engine: mathjax

google_site_verification: UK5Z3DkjNFOe8U_y4pFUaSc0cqYigDf3_JDHUIljLhM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
