theme: jekyll-theme-minimal
title: Thiago Scarelli
logo: /assets/img/logo.jpg
description: I'm a Ph.D Candidate at the Paris School of Economics (PSE) under the supervision of David N. Margolis. My current research projects focus on occupational decisions in developing regions.
google_analytics: UA-175203179-1
